// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Server/session
export const SERVER_CONNECT_SUCCESS = 'SERVER_CONNECT_SUCCESS';
export const SERVER_CONNECT_FAIL = 'SERVER_CONNECT_FAIL';
export const SERVER_DISCONNECT_SUCCESS = 'SERVER_DISCONNECT_SUCCESS';
export const HOST_SESSION_SEND = 'HOST_SESSION_SEND';
export const HOST_SESSION_SUCCESS = 'HOST_SESSION_SUCCESS';
export const JOIN_SESSION_SEND = 'JOIN_SESSION_SEND';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const NEW_PLAYER_JOINED = 'NEW_PLAYER_JOINED';
export const PLAYER_LEFT = 'PLAYER_LEFT';
export const SERVER_USERNAME_SEND = 'SERVER_USERNAME_SEND';
export const SERVER_USERNAME_SUCCESS = 'SERVER_USERNAME_SUCCESS';

// Articulate
export const ARTICULATE_SEND_TEAM_SELECT = 'ARTICULATE_SEND_TEAM_SELECT';
export const ARTICULATE_PLAYER_TEAM_SELECT = 'ARTICULATE_PLAYER_TEAM_SELECT';
export const ARTICULATE_SEND_STATE_CHANGE = 'ARTICULATE_SEND_STATE_CHANGE';
export const ARTICULATE_STATE_CHANGE_SUCCESS =
  'ARTICULATE_STATE_CHANGE_SUCCESS';
export const ARTICULATE_SEND_MODE_CHANGE = 'ARTICULATE_SEND_MODE_CHANGE';
export const ARTICULATE_MODE_CHANGE_SUCCESS = 'ARTICULATE_MODE_CHANGE_SUCCESS';
export const ARTICULATE_SEND_DATA_RESET = 'ARTICULATE_SEND_DATA_RESET';
export const ARTICULATE_DATA_RESET_SUCCESS = 'ARTICULATE_DATA_RESET_SUCCESS';
export const ARTICULATE_SEND_NEXT_ROUND = 'ARTICULATE_SEND_NEXT_ROUND';
export const ARTICULATE_NEXT_ROUND_SUCCESS = 'ARTICULATE_NEXT_ROUND_SUCCESS';
export const ARTICULATE_SEND_ROTA = 'ARTICULATE_SEND_ROTA';
export const ARTICULATE_ROTA_SUCCESS = 'ARTICULATE_ROTA_SUCCESS';
