export const SERVER_CONNECT_SUCCESS = 'SERVER_CONNECT_SUCCESS';
export const SERVER_CONNECT_FAIL = 'SERVER_CONNECT_FAIL';
export const SERVER_DISCONNECT_SUCCESS = 'SERVER_DISCONNECT_SUCCESS';
export const HOST_SESSION_SEND = 'HOST_SESSION_SEND';
export const HOST_SESSION_SUCCESS = 'HOST_SESSION_SUCCESS';
export const SERVER_USERNAME_SEND = 'SERVER_USERNAME_SEND';
export const SERVER_USERNAME_SUCCESS = 'SERVER_USERNAME_SUCCESS';
