export const SERVER_CONNECT_SUCCESS = 'SERVER_CONNECT_SUCCESS';
export const SERVER_CONNECT_FAIL = 'SERVER_CONNECT_FAIL';
export const SERVER_DISCONNECT_SUCCESS = 'SERVER_DISCONNECT_SUCCESS';
export const HOST_SESSION_SEND = 'HOST_SESSION_SEND';
export const HOST_SESSION_SUCCESS = 'HOST_SESSION_SUCCESS';
export const JOIN_SESSION_SEND = 'JOIN_SESSION_SEND';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const NEW_PLAYER_JOINED = 'NEW_PLAYER_JOINED';
export const PLAYER_LEFT = 'PLAYER_LEFT';
export const SERVER_USERNAME_SEND = 'SERVER_USERNAME_SEND';
export const SERVER_USERNAME_SUCCESS = 'SERVER_USERNAME_SUCCESS';

// Articulate
export const ARTICULATE_SEND_TEAM_SELECT = 'ARTICULATE_SEND_TEAM_SELECT';
export const ARTICULATE_PLAYER_TEAM_SELECT = 'ARTICULATE_PLAYER_TEAM_SELECT';
export const ARTICULATE_SEND_STATE_CHANGE = 'ARTICULATE_SEND_STATE_CHANGE';
export const ARTICULATE_STATE_CHANGE_SUCCESS =
  'ARTICULATE_STATE_CHANGE_SUCCESS';
